---
    - name: Configure udapeople infrastructure
      hosts: all
      user: ubuntu
      gather_facts: false
      vars:
        - ansible_python_interpreter: /usr/bin/python3
        - ansible_host_key_checking: false
        - ansible_stdout_callback: yaml
      tasks:
        - name: install  nodejs and npm
          apt:
            name: ["nodejs", "npm"]
            state: latest
            update_cache: yes

        - name: install angular 
          apt:
            name: angular-cli      